# Generated by Django 3.1 on 2020-08-31 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Имя автора')),
                ('birth_year', models.PositiveSmallIntegerField(verbose_name='Год рождения')),
                ('country', models.CharField(max_length=2, verbose_name='Страна')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=13, verbose_name='Международный стандартный книжный номер')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Аннотация')),
                ('year_release', models.PositiveSmallIntegerField(verbose_name='Год издания')),
                ('copy_count', models.PositiveSmallIntegerField(default=1, verbose_name='Число копий')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('date_issue', models.DateTimeField(blank=True, null=True, verbose_name='Книга выдана')),
                ('date_delivery', models.DateTimeField(blank=True, null=True, verbose_name='Книга должна быть сдана')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Имя друга')),
                ('address', models.CharField(max_length=128, verbose_name='Адрес')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронный адресс')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название издательства')),
            ],
        ),
        migrations.CreateModel(
            name='Inspiration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_library.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_library.book')),
                ('inspirer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspired_works', to='p_library.author')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='book_authors', through='p_library.Inspiration', to='p_library.Author', verbose_name='Авторы'),
        ),
        migrations.AddField(
            model_name='book',
            name='friend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_friend', to='p_library.friend', verbose_name='Книга одолжена другу'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_publisher', to='p_library.publisher', verbose_name='Издательство'),
        ),
    ]
